name: k8s-deployment-beta

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@main
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build container image
      run: docker build -t registry.digitalocean.com/k8s-private-registery/nodejs-test:$(echo $GITHUB_SHA | head -c7) .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/k8s-private-registery/nodejs-test:$(echo $GITHUB_SHA | head -c7)